import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;create table auth.users(id uuid primary key);create table storage.buckets(id text primary key,name text,public boolean);create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;grant usage on schema public,auth to anon,authenticated,service_role;grant execute on function auth.uid() to public;alter default privileges in schema public grant all on tables to service_role;alter default privileges in schema public grant all on sequences to service_role;`);
let base=fs.readFileSync(root+'supabase/base_ml_schema.sql','utf8');
base=base.replace(/do \$\$ begin alter publication[^\n]+\n/,'');
await db.exec(base);
const migration=fs.readFileSync(root+'supabase/migrations/20261007180805_employee_company_ml.sql','utf8');
await db.exec(migration);
const employee='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',owner='33333333-3333-4333-8333-333333333333';
await db.exec(`insert into auth.users values('${employee}'),('${other}'),('${owner}');`);
async function asUser(uid){await db.exec(`reset role;select set_config('request.jwt.claim.sub','${uid}',false);set role authenticated;`);}
async function denied(sql){let failed=false;try{await db.exec(sql)}catch{failed=true}assert(failed,'Must reject: '+sql.slice(0,70));}
await asUser(employee);
await db.exec(`insert into skill_passports(user_id,display_name,target_role,experience_years) values('${employee}','Alex','Data Analyst',3);insert into skill_logs(user_id,skill,kind,score,practiced_at) values('${employee}','Python','technical',75,now()-interval '1 day');`);
await denied(`insert into skill_logs(user_id,skill,kind,score,practiced_at,source) values('${employee}','SQL','technical',100,now(),'verified')`);
await denied(`insert into skill_passports(user_id,display_name) values('${other}','Not mine')`);
await denied(`update skill_passports set role_readiness_score=100 where user_id='${employee}'`);
await denied(`truncate table skill_logs`);
await denied(`select public.claim_inference_request('${employee}')`);
await asUser(other);
assert.equal((await db.query('select user_id from skill_passports')).rows.length,0);
assert.equal((await db.query('select id from skill_logs')).rows.length,0);
await asUser(owner);
const company=(await db.query(`insert into companies(owner_id,name) values('${owner}','Test company') returning id`)).rows[0].id;
assert.equal((await db.query('select user_id from skill_passports')).rows.length,0);
await asUser(employee);
await db.exec(`insert into passport_shares(user_id,company_id) values('${employee}','${company}')`);
await db.exec('reset role;set role service_role;');
await db.exec(`insert into model_registry(model_name,version,data_source,is_active,features,metrics) values('skill_passport_readiness_v2','test-v1','supabase',true,'[]','{}')`);
const analytics={user_id:employee,role_readiness_pred:75,readiness_band:'Strong coverage',technical_index:70,communication_score:80,task_fit_score:80,weighted_readiness_score:75,leadership_readiness_score:75,mentorship:{multiplier:1,observations:0},skill_decay:[],skill_gaps:[],data_quality:{},explanation:{summary:'test'},model_version:'test-v1',is_synthetic:false,input_hash:'test',feature_as_of:new Date(Date.now()+1000).toISOString(),scored_at:new Date().toISOString()};
const workload={user_id:employee,ratio:1.3,workload_review_flag:true,status:'review_workload',scored_at:new Date().toISOString()};
await db.query('select store_skill_analytics($1,$2)',[JSON.stringify(analytics),JSON.stringify(workload)]);
assert.equal((await db.query('select claim_inference_request($1) as claimed',[employee])).rows[0].claimed,true);
assert.equal((await db.query('select claim_inference_request($1) as claimed',[employee])).rows[0].claimed,false);
await asUser(owner);
assert.equal((await db.query('select user_id from skill_passports')).rows.length,1);
assert.equal((await db.query('select user_id from user_skill_analytics')).rows.length,1);
assert.equal((await db.query('select * from employee_workload_signals')).rows.length,0);
assert.equal((await db.query('select * from skill_logs')).rows.length,0);
await denied('select stagnation_prob from user_skill_analytics');
await denied(`insert into peer_assignments(company_id,senior_id,junior_id,skill,project_name,starts_at) values('${company}','${employee}','${other}','Python','Test project',now())`);
await asUser(employee);
await db.exec(`delete from passport_shares where company_id='${company}'`);
await asUser(owner);
assert.equal((await db.query('select user_id from skill_passports')).rows.length,0);
assert.equal((await db.query('select user_id from user_skill_analytics')).rows.length,0);
await db.exec('reset role;set role service_role;');
analytics.is_synthetic=true;
await assert.rejects(db.query('select store_skill_analytics($1,$2)',[JSON.stringify(analytics),JSON.stringify(workload)]));
analytics.is_synthetic=false;analytics.feature_as_of='2000-01-01T00:00:00Z';
await assert.rejects(db.query('select store_skill_analytics($1,$2)',[JSON.stringify(analytics),JSON.stringify(workload)]));
await db.close();console.log('Local PostgreSQL checks passed: migration applies; owner writes; consent gates; private workload; no forged verification; no score edits; no TRUNCATE; revoke access; service-only RPC; throttle; stale/demo rejection.');
