import Link from 'next/link';
import {ArrowUpRight,Fingerprint,Download} from 'lucide-react';
import '../portal.css';
const steps=[
 ['Choose a workspace','Employees maintain skill evidence and choose which companies can view their passport. Companies publish roles, view shared profiles and record mentorship assignments. The preview uses clearly labelled illustrative data.'],
 ['Connect the database','The existing Supabase project stores profiles, dated skill logs, project tasks and sharing permissions. The approved employee/company migration is installed in the existing project. Row-level security checks whose records each account can read or change.'],
 ['Sign in with Supabase','Supabase handles email/password and, once configured, Google sign-in. The website receives a session. API routes verify it before reading or saving data. Redirects are a normal part of OAuth; the callback must return to your public Vercel domain.'],
 ['Add evidence','Create an employee profile. Record at least one technical skill and one communication log, with scores from 0 to 100. Entries added by employees are self-reported. Skill recency uses a configurable half-life; workload is a private task/capacity check.'],
 ['Train in Google Colab','Open the supplied notebook, upload the ML source ZIP and run the explicitly synthetic software test first. For real training, provide consented historical snapshots and independent skill-assessment labels. Optuna tunes XGBoost; SHAP explains it; ONNX export is checked against the original predictions.'],
 ['Review and activate a model','Real bundles upload to private Supabase Storage and are registered inactive. Review validation and the model card before activation. Synthetic bundles cannot be published by the pipeline. Training on real evidence has not been completed yet.'],
 ['Score with a lightweight server','An authenticated request to /api/inference loads the active ONNX model, calculates fresh explanations and atomically saves prepared analytics. The worker needs a server-only Supabase key. The frontend reads the results; training libraries never run in the browser.'],
 ['Deploy the upgrade','Build and test the project, apply the approved database migration, set Vercel environment variables, then deploy to the same Vercel project. Test with separate employee and company accounts before inviting friends. The complete downloadable guide has exact commands and URLs.']
];
export default function Guide(){return <div className="sp-landing"><header><Link className="sp-logo" href="/"><Fingerprint/>skill<span>passport</span></Link><Link className="sp-btn" href="/employee">Open workspace<ArrowUpRight size={16}/></Link></header><main style={{maxWidth:900,textAlign:'left',paddingTop:45}}><p className="sp-eyebrow" style={{justifyContent:'flex-start'}}>FROM FIRST LOG TO LIVE INSIGHT</p><h1 style={{fontSize:48,letterSpacing:-2}}>How the pieces<br/>work together.</h1><p className="sp-landing-intro" style={{marginLeft:0}}>Vercel serves the website. Supabase stores and protects the data. Colab trains the model. A small Python function runs it.</p><a href="/Skill_Passport_Beginner_Guide.md" download className="sp-btn sp-btn-dark" style={{margin:'26px 0'}}><Download size={16}/>Download the complete setup guide</a><a href="/Skill_Passport_Architecture_Map.md" download className="sp-btn" style={{marginLeft:12}}>Download the connection map</a>{steps.map(([title,text],i)=><section className="sp-card" key={title} style={{textAlign:'left'}}><p className="sp-eyebrow" style={{justifyContent:'flex-start'}}>STEP {String(i+1).padStart(2,'0')}</p><h2 style={{fontSize:22,margin:'8px 0 12px'}}>{title}</h2><p style={{fontSize:13,color:'#7b8970',lineHeight:1.9}}>{text}</p></section>)}<section className="sp-card"><h2 style={{fontSize:22,marginBottom:12}}>Explain it to a judge</h2><p style={{fontSize:14,lineHeight:1.9,color:'#687d5d'}}>“Skill Passport helps employees turn skill evidence into an evolving development profile. Companies can see only the passports people choose to share. We account for recent practice, show the model’s main drivers, and recognize observed peer growth. We train offline in Colab and run small ONNX models in production. The current preview demonstrates the workflow with illustrative data; real predictive performance still needs independent assessment data and validation.”</p></section></main><footer>Skill Passport<Link href="/">Back to home</Link></footer></div>}
